### ISSUE TITLE
How to use Shape Emitters?

### ISSUE THREAD

**Issue by shshwdr** [jongallant/Unity-Bullet-Hell#10]
This is awesome work! But I haven't figured out how to use the shape one. I tried:
1. add a ProjectileEmitterShape, then add the square shape on it, but when I run the game this code conplaints:

```
protected override void UpdateProjectiles(float tick)
        {
            throw new System.NotImplementedException();
        }
```
2. I tried to find out where to add the shape item on the ProjectileEmitterAdvanced but failed to find it.
3. I also didn't find an example prefab of it...
Let me know if I missed anything or how can I make it work. Again this is a great project thanks for sharing!

**Comment by jongallant** [comment]
I pushed a quick fix for the shape emitter.

**Comment by shshwdr** [comment]
thanks, it works perfectly!
