### ISSUE TITLE
sorting layer

### ISSUE THREAD

**Issue by mlanci** [jongallant/Unity-Bullet-Hell#11]
I've been trying a bunch of different things and i'm falling short every time. Is it possible to somehow change the sorting layer? I'm using tilemaps and so the bullets are spawning "behind" the tilemaps..

**Comment by jongallant** [comment]
You can change the sorting layer on the Material.  Looks like the property is called z-indez by error:
![Capture](https://user-images.githubusercontent.com/748973/114624892-ca17af80-9c87-11eb-9245-9f22f1c46cb0.PNG)

Alternatively, set the position.z value of the object you want to render in front to a higher value.

**Comment by mlanci** [comment]
AH This is a life saver, so happy this is working properly now.

I saw you had made an update to the shape emitter, is that working now? I tried with new master branch and can't seem to get it shooting anything. Maybe I'm not utilizing it properly..

**Comment by jongallant** [comment]
The sample scene should demonstrate how the Shape Emitter works.
