### ISSUE TITLE
bullets are not shown in build version

### ISSUE THREAD

**Issue by shshwdr** [jongallant/Unity-Bullet-Hell#12]
It works perfectly in unity, but when I tried to build the SampleScene in either windows or webgl, the bullets do not load and this is the error message I got:

```
ArgumentNullException: Value cannot be null.
Parameter name: shader
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
NullReferenceException: Object reference not set to an instance of an object
```

I'm using Unity 2020.3.0f1, I'm on the latest master. I tried to turn off Enable GPU instancing in materials but it makes no difference.

**Comment by jongallant** [comment]
I had fix this previously, Unity was stripping out the shader.  I added them as always included shaders, and it is still not working in Build mode.  I will need to investigate further.  Seems Unity 2020 does not like something with these shaders.

**Comment by shshwdr** [comment]
hmm, I tested on 2019.4.24(I copied the Unity-Bullet-Hell folder to a newly created project because otherwise, it has some weird issue after downgrade) but still can't see bullets in the build.

**Comment by shshwdr** [comment]
ok I use the older commit 0ea8b15372fa61bb7e7c4cea109fbd0ba317f02e and load with Unity 2019.4.24, the bullets show correctly in windows build, but not in web build. The projectiles number on the top left corner increased correctly, and there is no warning. But I can't see the bullets...

**Comment by jongallant** [comment]
Fixed in latest.

**Comment by JiaChen-Zeng** [comment]
I'm using the latest commit version with Unity 2020.3.15f2. I also have this problem with WebGL build. Has this issue been solved? The error message is 

```
ArgumentNullException: Value cannot be null.
Parameter name: shader
```

The message has gone after I added the shader to the project settings. But the bullets aren't displaying still.
