### ISSUE TITLE
Changing texture doesn't affect the appearance of the projectile

### ISSUE THREAD

**Issue by JiaChen-Zeng** [jongallant/Unity-Bullet-Hell#15]
I can't find a way to change the appearance of the projectile. Even if I set the texture to a square, it shows as a circle.

**Comment by jongallant** [comment]
You need to set the texture in the Projectile Prefab.

**Comment by JiaChen-Zeng** [comment]
I've already set the texture but it wouldn't work. It looks like a bug.

![image](https://user-images.githubusercontent.com/3676278/147969915-1b837018-3f6a-484b-876e-3877bf0b042d.png)

**Comment by jongallant** [comment]
Ah.  You are still using the sphere mesh.  Try changing the mesh to a quad
instead.

**Comment by JiaChen-Zeng** [comment]
Thanks. Changing the mesh to a quad works!
