### ISSUE TITLE
Doesn't seem to work (Unity 2019.1.13f1)

### ISSUE THREAD

**Issue by snikolictech** [jongallant/Unity-Bullet-Hell#4]
Opened in Unity 2019.1.13f1, loaded the two sample scenes and neither showed any bullets.

The bullet count did increase though. Projectile prefab wasn't present in the projectile slot on one emitter. Added it, but to no avail.

Maybe it's a shader issue? I have an older graphics card (8800GT)

**Comment by jongallant** [comment]
It is possible that card does not support GPU instancing.  Try disabling GPU instancing on the Material properties to see if it will draw the projectiles.

If that is the case, then you will have a significant performance impact when turning this feature off.  It should still work, but it will not take advantage of the draw call instancing.

**Comment by snikolictech** [comment]
Instancing never caused a problem for me before. Nevertheless, disabled GPU instancing on Projectile1Material and Projectile2Material made no difference. Also tried it in an earlier version of Unity 2019 made no difference.

**Comment by jongallant** [comment]
Very strange.  I just imported it in a 2019.1.18 build, and it worked without having to change anything.
I am unsure as to why it would not be rendering the particles on your PC.

**Comment by jongallant** [comment]
Can you try explicitly setting your Camera clipping planes to (-1000, 1000)
See if this allows the particles to render.

**Comment by jongallant** [comment]
Should be fixed in latest version.
